stages:
  - deploy

.deploy_staging_default: &deploy_staging_default
  stage: deploy
  # 通过 shell 执行的
  script:
    - pwd
    # 避免克隆下来的 .sh 文件没有执行权限导致执行失败，预先添加执行权限
    # 如果报错：`sudo: no tty present and no askpass program specified` 则需要去掉sudo
    - sudo chmod -R a+x .
    # 执行部署脚本
    - sudo ./ci/deploy_staging.sh

  # tags 标签表示这个 CI 任务在会被分配给哪些 Runner，只有包含如下 tags 中任意一个或多个的 Runner 才会执行这个任务。
  tags:
    - test
    - deploy

# 合并到 test 分支时执的脚本，通过 only 字段约束为 merge_requests 情况下 目标分支名称为 “test” 时才会执行。
deploy_staging1:
  <<: *deploy_staging_default
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "test"

# 在 test 分支上直接操作时执行的脚本。
deploy_staging2:
  <<: *deploy_staging_default
  only:
    - test